### PR TITLE
cvOSCcv: restore connection

### PR DESCRIPTION
**Pull request by jfrey-xx**
Hello,

I am trying to find ways to command VCV Rack from outside, without the need to interact with the GUI. Your OSC module might just be what I need, however there is one inconvenience: upon start I still have to "enable" each module manually.

Hence here is a proposal to save the last state of the module (connection up or not) and restore this state when a patch is loaded.

### CODE REVIEW

**Comment by chichian** [comment]
Hi jfrey-xx,

We think this is a good addition, however some users may not want this. How do you feel if this was a setting on cvOSCcv (Auto-Reconnect On Load)?
 
We would make it pretty much the same, just an extra bool stored in the json and if true and it was enabled, then it would connect. I would have to add some place on the module or in context menu to set this, but that can be done.

**Comment by jfrey-xx** [comment]
Indeed there might be some cases where one might not want to open too many ports at once, even thought it is about restoring a previous state. Actually I considered adding a specific option to let users device... but that was beyond my reach, I did not want to touch the UI. If you can find a spot for a checkbox that would be perfect :)

**Comment by chichian** [comment]
Hi. 

We've added a little button for this in the OSC configuration screen in the latest release [v0.6.3](https://github.com/j4s0n-c/trowaSoft-VCV/releases/tag/v0.6.3). 

Thanks!

**Comment by jfrey-xx** [comment]
Thank you for the feature, it works perfectly :)

**Pull request closed without merging**
